### ISSUE TITLE
NGX USWDS Basic Table Margin Width-full add on

### ISSUE THREAD

**Issue by bserrano1** [GSA/ngx-uswds#77]
Components Involved
Please list the common component(s) involved that you're experiencing an issue with
NGX USWDS Table Basic
https://gsa.github.io/ngx-uswds/?path=/story/components-table--basic&args=striped:true;borderless:false;compact:true;stacked:true;stackedHeader:true

Expected Behavior
How you expect the listed component(s) to function

Table should not have additional margins added to the top, bottom or right.
![image](https://user-images.githubusercontent.com/26351294/188941721-66e5b838-0c78-4f33-b3e9-eef90c811a33.png)

Mobile view should look like the following:
![image](https://user-images.githubusercontent.com/26351294/188941945-2f090941-a4e3-49d7-a9cb-eab62498c1a1.png)

Actual Behavior
How the listed component(s) actually function

Current table has default Margin surrounding the table which is causing issues with implementation on our page.
![image](https://user-images.githubusercontent.com/26351294/188941983-557bbd19-607b-470a-9c73-40759b3b5b61.png)
![image](https://user-images.githubusercontent.com/26351294/188942009-2ee1e937-65cc-48d9-be1d-a72b81c6dc5a.png)

Mobile view looks need changes to match our design mock:
![image](https://user-images.githubusercontent.com/26351294/188942064-fee8987d-e87e-4970-843e-e4481846be4f.png)
![image](https://user-images.githubusercontent.com/26351294/188942093-b09ca100-e049-44fc-940d-f0dad7edfd5d.png)

Your Environment
Angular Version: X.Y.Z
@gsa-sam packages version: X.Y.Z (Please list individually if all packages are not same version)

Angular Version: "^12.2.15"
GSA Packages:
@gsa-sam/components@12.0.12
@gsa-sam/sam-material-extensions@12.0.12
@gsa-sam/sam-formly@12.0.12
@gsa-sam/layout@12.0.1
@gsa-sam/layouts@12.0.1
@gsa-sam/ngx-uswds@12.0.3
@gsa-sam/ngx-uswds-icons@12.0.0-beta.2
@gsa-sam/sam-styles@0.0.143
@gsa-sam/shared@12.0.1

Ticket Number
Please provide your JIRA ticket number that is dependent on this fix. If there is none, please create
one to validate the issue once the fix has been released. DO NOT provide the url, please ONLY
provide the ticket number.
IAE-XYZ

JIRA Ticket: IAEMOD-3851

Additional context
Screenshots / recordings, minimal reproduction on stackblitz, steps to reproduce, code snippets, etc.

**Comment by davereed** [comment]
I don't believe the issue is margins, the table data is just not sufficient to make the table take up the full width. That said, it wouldn't hurt for us to add styling for a forced full width table.
