### ISSUE TITLE
Formly Integration

### ISSUE THREAD

**Issue by JoeH-CGI** [GSA/ngx-uswds#81]
Hi, your Formly examples all show this import:

import { UsaFormlyModule } from "@gsa-sam/uswds-formly";

i cant even find that repo... tried to npm install it... says cant be found...

**Comment by JoeH-CGI** [comment]
is this library dead? no responses to issues from months ago... if the Gov wants to push USWDS, it needs to support it. Don't ask devs to use this stuff if you can't support modern JS frameworks.

**Comment by davereed** [comment]
@JoeH-CGI Thank you for your feedback. The team working on this library is not the same one as the official USWDS UI Framework. We created this open source Angular component library for SAM.gov and we plan to continue supporting it for the foreseeable future. All of the open issues are from developers on our project and we address them based on the project priorities. 

The module you are looking for is not feature complete and that is the reason we hadn't pushed it to NPM, but you can find it here within the repository:
https://github.com/GSA/ngx-uswds/blob/main/projects/uswds-formly/src/lib/formly.module.ts

If you don't mind sharing, what project(s) are you implementing this for?

**Comment by JoeH-CGI** [comment]
Thanks for your response. I do work for [A Government Agency], and almost all projects are React or Angular. They specify a preference for USWDS and this is the only Angular library I have found which supports that. There are obvious issues using the base USWDS library in either React or Angular projects - namely the amount of code needed to be written which should be abstracted to a library; hence the need for a library like this.

As a developer, i find it frustrating that the government is pushing the use of USWDS when there is limited support for modern javascript frameworks.

**Comment by JoeH-CGI** [comment]
well, i couldnt get this to build

![image](https://user-images.githubusercontent.com/81175836/198713086-02e1f146-3c81-47e3-a67f-c748b4b82913.png)

**Comment by JoeH-CGI** [comment]
so i had to build uswds-components first... but i had to fix some directive export issues with that. then i could build uswds-formly

still doesnt actually seem to work... getting errors binding to elements because ngIf isnt a know attribute. Thats usually an issue with not importing the Common Module, but i dunno.

**Comment by davereed** [comment]
We will try to address this in the upcoming week. We had a few high priority items to finish first.

**Comment by yerramshilpa** [comment]
@JoeH-CGI @davereed  There was an issue with the release, uswds-formly was never released to npm, I released new version for the both @gsa-sam/ngx-uswds@12.0.4 and @gsa-sam/uswds-formly@12.0.4 use these version for the formly integration

**Comment by JoeH-CGI** [comment]
really do appreciate the effort... that said, when i install 12.0.4 of each library listed above, i get the following angular compile errors. I think these are the same as i was seeing when i was trying to build this locally.
![image](https://user-images.githubusercontent.com/81175836/199630769-1e6b5d43-7487-48d4-b2c2-f05c34ed9ce4.png)

**Comment by JoeH-CGI** [comment]
so, im on angular 14, which probably has something to do with this. i think i resolved in your package locally by changing some of the imported js stubs (which were outdated)

**Comment by davereed** [comment]
@JoeH-CGI We have also updated the code sandbox so you can use those as a reference for setting it up. You can find those by clicking into the code preview tab on any demo and then the button to the right that says "Open Sandbox".

Here is the link to the input sandbox: https://codesandbox.io/s/o8y6i5

Right now we support v12 and v13 of Angular.

**Comment by JoeH-CGI** [comment]
thanks - i really do appreciate you all looking at this and resolving issues (your response has been great), but because i'll be using angular 14 (and USWDS 3.x) i think im just going to move forward with the Bootstrap Formly package and try to apply similar styles to USWDS.

**Comment by davereed** [comment]
You should be able to use USWDS 3.x with our library, the classes haven't really changed, it was mostly an internal change they made. 

We will be updating to v14 in the next couple of months, so if you aren't forced to use v14 you could just upgrade later. 

Closing the topic since the issue has been resolved.
